### ISSUE TITLE
Other licensing options?

### ISSUE THREAD

**Issue by spacepluk** [carocad/hugsql#13]
I wanted to give this a try in a React Native application but as far as I know the LGPL is incompatible with the mobile app stores distribution model.  Would you consider a more permissive license?
Thanks!

**Comment by carocad** [comment]
hey @spacepluk, in general, the LGPL only restricts that people making modifications to `hugsql` itself would need to disclose the modified hugsql version. However, using it in your app doesn't have any impact on it. Furthermore, hugsql is not included in your app as it is only a code generator so its code is in no way related to the code you shipped.

Hope it helps.

PS: closing this as I don't see any issue with the current license. Let me know if you see an issue with the argument above.

**Comment by spacepluk** [comment]
@carocad I was assuming there would be some bits of hugsql in the generated code that would clash with the distribution requirements. Thanks for the clarification!  I'll be happy to share a PR with any modifications nonetheless.
